# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0c43f4280ef25baa86144706d230fda383aec94a5fa529ecf196c2add53ff8c63f9c256a7c7e21676ea9d29e95bba918f0ab1169e6883c9741b084acd4311ec2

test:
  secret_key_base: 6cfe2de465dde5d88c51a7ce8f605f417d61a7077971b9dacf65d6fb84802f3a55d739a853701b7482fe6372799bfba66c8029dd13c8e28f7beef9716ba78b9f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
